indexer: main_rendered.cpp
	g++ -Wall -pedantic -O2 -Wno-unused-result main_rendered.cpp -o indexer -std=c++11

asm: main.cpp
	g++ -Wall -pedantic -O0 -Wno-unused-result -g main.cpp -o main.asm -std=c++11 -S
